module.exports = [
  {
    "color": "Color",
    "director_name": "Thomas Carter",
    "num_critic_for_reviews": 50,
    "duration": 115,
    "director_facebook_likes": 49,
    "actor_3_facebook_likes": 100,
    "actor_2_name": "Matthew Daddario",
    "actor_1_facebook_likes": 116,
    "gross": 30127963,
    "genres": "Drama|Family|Sport",
    "actor_1_name": "Jessie T. Usher",
    "movie_title": "When the Game Stands Tall ",
    "num_voted_users": 12596,
    "cast_total_facebook_likes": 525,
    "actor_3_name": "Ser'Darius Blain",
    "facenumber_in_poster": 0,
    "plot_keywords": "coach|high school football",
    "movie_imdb_link": "http://www.imdb.com/title/tt2247476/?ref_=fn_tt_tt_1",
    "num_user_for_reviews": 64,
    "language": "English",
    "country": "USA",
    "content_rating": "PG",
    "budget": 15000000,
    "title_year": 2014,
    "actor_2_facebook_likes": 110,
    "imdb_score": 6.7,
    "aspect_ratio": 1.85,
    "movie_facebook_likes": 0
  },
  {
    "color": "Color",
    "director_name": "Wayne Wang",
    "num_critic_for_reviews": 96,
    "duration": 106,
    "director_facebook_likes": 61,
    "actor_3_facebook_likes": 649,
    "actor_2_name": "Luke Benward",
    "actor_1_facebook_likes": 907,
    "gross": 32645546,
    "genres": "Comedy|Drama|Family",
    "actor_1_name": "Cicely Tyson",
    "movie_title": "Because of Winn-Dixie ",
    "num_voted_users": 8427,
    "cast_total_facebook_likes": 3462,
    "actor_3_name": "Eva Marie Saint",
    "facenumber_in_poster": 5,
    "plot_keywords": "10 year old|dog|florida|girl|supermarket",
    "movie_imdb_link": "http://www.imdb.com/title/tt0317132/?ref_=fn_tt_tt_1",
    "num_user_for_reviews": 88,
    "language": "English",
    "country": "USA",
    "content_rating": "PG",
    "budget": 14000000,
    "title_year": 2005,
    "actor_2_facebook_likes": 807,
    "imdb_score": 6.4,
    "aspect_ratio": 1.85,
    "movie_facebook_likes": 1000
  },
  {
    "color": "Color",
    "director_name": "Gina Prince-Bythewood",
    "num_critic_for_reviews": 68,
    "duration": 124,
    "director_facebook_likes": 107,
    "actor_3_facebook_likes": 865,
    "actor_2_name": "Sanaa Lathan",
    "actor_1_facebook_likes": 1000,
    "gross": 27441122,
    "genres": "Drama|Romance|Sport",
    "actor_1_name": "Alfre Woodard",
    "movie_title": "Love & Basketball ",
    "num_voted_users": 14322,
    "cast_total_facebook_likes": 5135,
    "actor_3_name": "Omar Epps",
    "facenumber_in_poster": 0,
    "plot_keywords": "basketball movie|female basketball player|high school|nba|title directed by female",
    "movie_imdb_link": "http://www.imdb.com/title/tt0199725/?ref_=fn_tt_tt_1",
    "num_user_for_reviews": 116,
    "language": "English",
    "country": "USA",
    "content_rating": "PG-13",
    "budget": 15000000,
    "title_year": 2000,
    "actor_2_facebook_likes": 886,
    "imdb_score": 7.2,
    "aspect_ratio": 1.85,
    "movie_facebook_likes": 0
  },
  {
    "color": "Color",
    "director_name": "George Armitage",
    "num_critic_for_reviews": 111,
    "duration": 107,
    "director_facebook_likes": 5,
    "actor_3_facebook_likes": 141,
    "actor_2_name": "Michael Cudlitz",
    "actor_1_facebook_likes": 893,
    "gross": 28014536,
    "genres": "Action|Comedy|Crime|Romance|Thriller",
    "actor_1_name": "Minnie Driver",
    "movie_title": "Grosse Pointe Blank ",
    "num_voted_users": 73347,
    "cast_total_facebook_likes": 2044,
    "actor_3_name": "Mitchell Ryan",
    "facenumber_in_poster": 1,
    "plot_keywords": "assassin|high school|high school reunion|reunion|suburb",
    "movie_imdb_link": "http://www.imdb.com/title/tt0119229/?ref_=fn_tt_tt_1",
    "num_user_for_reviews": 296,
    "language": "English",
    "country": "USA",
    "content_rating": "R",
    "budget": 15000000,
    "title_year": 1997,
    "actor_2_facebook_likes": 822,
    "imdb_score": 7.4,
    "aspect_ratio": 1.85,
    "movie_facebook_likes": 0
  },
  {
    "color": "Color",
    "director_name": "Phil Traill",
    "num_critic_for_reviews": 128,
    "duration": 99,
    "director_facebook_likes": 3,
    "actor_3_facebook_likes": 628,
    "actor_2_name": "Katy Mixon",
    "actor_1_facebook_likes": 14000,
    "gross": 33860010,
    "genres": "Comedy|Romance",
    "actor_1_name": "Bradley Cooper",
    "movie_title": "All About Steve ",
    "num_voted_users": 33088,
    "cast_total_facebook_likes": 16461,
    "actor_3_name": "Beth Grant",
    "facenumber_in_poster": 3,
    "plot_keywords": "blind date|crossword puzzle|eccentric|fall|mine shaft",
    "movie_imdb_link": "http://www.imdb.com/title/tt0881891/?ref_=fn_tt_tt_1",
    "num_user_for_reviews": 143,
    "language": "English",
    "country": "USA",
    "content_rating": "PG-13",
    "budget": 15000000,
    "title_year": 2009,
    "actor_2_facebook_likes": 982,
    "imdb_score": 4.8,
    "aspect_ratio": 1.85,
    "movie_facebook_likes": 0
  },
  {
    "color": "Color",
    "director_name": "Joe Berlinger",
    "num_critic_for_reviews": 160,
    "duration": 90,
    "director_facebook_likes": 31,
    "actor_3_facebook_likes": 162,
    "actor_2_name": "Erica Leerhsen",
    "actor_1_facebook_likes": 193,
    "gross": 26421314,
    "genres": "Adventure|Fantasy|Horror|Mystery|Thriller",
    "actor_1_name": "Kim Director",
    "movie_title": "Book of Shadows: Blair Witch 2 ",
    "num_voted_users": 28964,
    "cast_total_facebook_likes": 608,
    "actor_3_name": "Kurt Loder",
    "facenumber_in_poster": 0,
    "plot_keywords": "convenience store|digit in title|punctuation in title|violence|witch",
    "movie_imdb_link": "http://www.imdb.com/title/tt0229260/?ref_=fn_tt_tt_1",
    "num_user_for_reviews": 457,
    "language": "English",
    "country": "USA",
    "content_rating": "R",
    "budget": 15000000,
    "title_year": 2000,
    "actor_2_facebook_likes": 184,
    "imdb_score": 4,
    "aspect_ratio": 1.85,
    "movie_facebook_likes": 949
  },
  {
    "color": "Color",
    "director_name": "Andrew Fleming",
    "num_critic_for_reviews": 93,
    "duration": 101,
    "director_facebook_likes": 26,
    "actor_3_facebook_likes": 266,
    "actor_2_name": "Rachel True",
    "actor_1_facebook_likes": 838,
    "gross": 24881000,
    "genres": "Drama|Fantasy|Horror|Thriller",
    "actor_1_name": "Christine Taylor",
    "movie_title": "The Craft ",
    "num_voted_users": 57140,
    "cast_total_facebook_likes": 1812,
    "actor_3_name": "Brenda Strong",
    "facenumber_in_poster": 0,
    "plot_keywords": "coven|occult|outcast|spell|witch",
    "movie_imdb_link": "http://www.imdb.com/title/tt0115963/?ref_=fn_tt_tt_1",
    "num_user_for_reviews": 195,
    "language": "English",
    "country": "USA",
    "content_rating": "R",
    "budget": 15000000,
    "title_year": 1996,
    "actor_2_facebook_likes": 328,
    "imdb_score": 6.2,
    "aspect_ratio": 1.85,
    "movie_facebook_likes": 6000
  },
  {
    "color": "Color",
    "director_name": "Woody Allen",
    "num_critic_for_reviews": 278,
    "duration": 119,
    "director_facebook_likes": 11000,
    "actor_3_facebook_likes": 400,
    "actor_2_name": "Mark Gatiss",
    "actor_1_facebook_likes": 19000,
    "gross": 23089926,
    "genres": "Drama|Romance|Thriller",
    "actor_1_name": "Scarlett Johansson",
    "movie_title": "Match Point ",
    "num_voted_users": 166269,
    "cast_total_facebook_likes": 20391,
    "actor_3_name": "Penelope Wilton",
    "facenumber_in_poster": 3,
    "plot_keywords": "extramarital affair|infidelity|irony of fate|surprise ending|tennis",
    "movie_imdb_link": "http://www.imdb.com/title/tt0416320/?ref_=fn_tt_tt_1",
    "num_user_for_reviews": 735,
    "language": "English",
    "country": "UK",
    "content_rating": "R",
    "budget": 15000000,
    "title_year": 2005,
    "actor_2_facebook_likes": 567,
    "imdb_score": 7.7,
    "aspect_ratio": 1.85,
    "movie_facebook_likes": 0
  },
  {
    "color": "Color",
    "director_name": "Elizabeth Allen Rosenbaum",
    "num_critic_for_reviews": 81,
    "duration": 103,
    "director_facebook_likes": 20,
    "actor_3_facebook_likes": 125,
    "actor_2_name": "Hutch Dano",
    "actor_1_facebook_likes": 512,
    "gross": 26161406,
    "genres": "Adventure|Comedy|Family|Fantasy",
    "actor_1_name": "Sierra McCormick",
    "movie_title": "Ramona and Beezus ",
    "num_voted_users": 13874,
    "cast_total_facebook_likes": 1002,
    "actor_3_name": "Jason Spevack",
    "facenumber_in_poster": 2,
    "plot_keywords": "aunt|cat|death of pet|girl|no opening credits",
    "movie_imdb_link": "http://www.imdb.com/title/tt0493949/?ref_=fn_tt_tt_1",
    "num_user_for_reviews": 52,
    "language": "English",
    "country": "USA",
    "content_rating": "G",
    "budget": 15000000,
    "title_year": 2010,
    "actor_2_facebook_likes": 316,
    "imdb_score": 6.7,
    "aspect_ratio": 2.35,
    "movie_facebook_likes": 0
  },
  {
    "color": "Color",
    "director_name": "James Ivory",
    "num_critic_for_reviews": 58,
    "duration": 134,
    "director_facebook_likes": 133,
    "actor_3_facebook_likes": 258,
    "actor_2_name": "Peter Vaughan",
    "actor_1_facebook_likes": 12000,
    "gross": 22954968,
    "genres": "Drama|Romance",
    "actor_1_name": "Anthony Hopkins",
    "movie_title": "The Remains of the Day ",
    "num_voted_users": 45703,
    "cast_total_facebook_likes": 12749,
    "actor_3_name": "Ben Chaplin",
    "facenumber_in_poster": 1,
    "plot_keywords": "butler|housekeeper|manor|servant|service",
    "movie_imdb_link": "http://www.imdb.com/title/tt0107943/?ref_=fn_tt_tt_1",
    "num_user_for_reviews": 156,
    "language": "English",
    "country": "UK",
    "content_rating": "PG",
    "budget": 11500000,
    "title_year": 1993,
    "actor_2_facebook_likes": 310,
    "imdb_score": 7.9,
    "aspect_ratio": 2.35,
    "movie_facebook_likes": 0
  },
  {
    "color": "Color",
    "director_name": "Paul Thomas Anderson",
    "num_critic_for_reviews": 153,
    "duration": 155,
    "director_facebook_likes": 0,
    "actor_3_facebook_likes": 170,
    "actor_2_name": "Nicole Ari Parker",
    "actor_1_facebook_likes": 3000,
    "gross": 26384919,
    "genres": "Drama",
    "actor_1_name": "Don Cheadle",
    "movie_title": "Boogie Nights ",
    "num_voted_users": 189032,
    "cast_total_facebook_likes": 3677,
    "actor_3_name": "Nina Hartley",
    "facenumber_in_poster": 15,
    "plot_keywords": "1970s|adult entertainment industry|nightclub|porn industry|san fernando valley california",
    "movie_imdb_link": "http://www.imdb.com/title/tt0118749/?ref_=fn_tt_tt_1",
    "num_user_for_reviews": 560,
    "language": "English",
    "country": "USA",
    "content_rating": "R",
    "budget": 15000000,
    "title_year": 1997,
    "actor_2_facebook_likes": 360,
    "imdb_score": 7.9,
    "aspect_ratio": 2.35,
    "movie_facebook_likes": 0
  },
  {
    "color": "Color",
    "director_name": "Robert Harmon",
    "num_critic_for_reviews": 25,
    "duration": 94,
    "director_facebook_likes": 11,
    "actor_3_facebook_likes": 232,
    "actor_2_name": "Rosanna Arquette",
    "actor_1_facebook_likes": 1000,
    "gross": 22189039,
    "genres": "Action|Crime|Drama|Romance|Thriller",
    "actor_1_name": "Kieran Culkin",
    "movie_title": "Nowhere to Run ",
    "num_voted_users": 17074,
    "cast_total_facebook_likes": 2210,
    "actor_3_name": "Joss Ackland",
    "facenumber_in_poster": 0,
    "plot_keywords": "business|escaped convict|farm|motorcycle|widow",
    "movie_imdb_link": "http://www.imdb.com/title/tt0107711/?ref_=fn_tt_tt_1",
    "num_user_for_reviews": 55,
    "language": "English",
    "country": "USA",
    "content_rating": "R",
    "budget": 15000000,
    "title_year": 1993,
    "actor_2_facebook_likes": 605,
    "imdb_score": 5.5,
    "aspect_ratio": 1.85,
    "movie_facebook_likes": 466
  },
  {
    "color": "Color",
    "director_name": "Michael Mayer",
    "num_critic_for_reviews": 46,
    "duration": 95,
    "director_facebook_likes": 15,
    "actor_3_facebook_likes": 461,
    "actor_2_name": "Danny Pino",
    "actor_1_facebook_likes": 1000,
    "gross": 20998709,
    "genres": "Adventure|Drama|Family",
    "actor_1_name": "Alison Lohman",
    "movie_title": "Flicka ",
    "num_voted_users": 6095,
    "cast_total_facebook_likes": 3845,
    "actor_3_name": "Tim McGraw",
    "facenumber_in_poster": 0,
    "plot_keywords": "father son relationship|horse|horse ranch|ranch|wild mustang",
    "movie_imdb_link": "http://www.imdb.com/title/tt0434215/?ref_=fn_tt_tt_1",
    "num_user_for_reviews": 76,
    "language": "English",
    "country": "USA",
    "content_rating": "PG",
    "budget": 15000000,
    "title_year": 2006,
    "actor_2_facebook_likes": 786,
    "imdb_score": 6.2,
    "aspect_ratio": 2.35,
    "movie_facebook_likes": 1000
  },
  {
    "color": "Color",
    "director_name": "Martin Weisz",
    "num_critic_for_reviews": 161,
    "duration": 89,
    "director_facebook_likes": 7,
    "actor_3_facebook_likes": 399,
    "actor_2_name": "Daniella Alonso",
    "actor_1_facebook_likes": 919,
    "gross": 20801344,
    "genres": "Horror",
    "actor_1_name": "Jeff Kober",
    "movie_title": "The Hills Have Eyes II ",
    "num_voted_users": 49721,
    "cast_total_facebook_likes": 2559,
    "actor_3_name": "Jacob Vargas",
    "facenumber_in_poster": 0,
    "plot_keywords": "desert|fight|hill|murder|mutant",
    "movie_imdb_link": "http://www.imdb.com/title/tt0800069/?ref_=fn_tt_tt_1",
    "num_user_for_reviews": 211,
    "language": "English",
    "country": "USA",
    "content_rating": "R",
    "budget": 15000000,
    "title_year": 2007,
    "actor_2_facebook_likes": 557,
    "imdb_score": 5.1,
    "aspect_ratio": 2.35,
    "movie_facebook_likes": 0
  },
  {
    "color": "Color",
    "director_name": "Lajos Koltai",
    "num_critic_for_reviews": 73,
    "duration": 160,
    "director_facebook_likes": 45,
    "actor_3_facebook_likes": 0,
    "actor_2_name": "Péter Fancsikai",
    "actor_1_facebook_likes": 9,
    "gross": 195888,
    "genres": "Drama|Romance|War",
    "actor_1_name": "Marcell Nagy",
    "movie_title": "Fateless ",
    "num_voted_users": 5603,
    "cast_total_facebook_likes": 11,
    "actor_3_name": "Bálint Péntek",
    "facenumber_in_poster": 0,
    "plot_keywords": "bus|death|gay slur|hatred|jewish",
    "movie_imdb_link": "http://www.imdb.com/title/tt0367082/?ref_=fn_tt_tt_1",
    "num_user_for_reviews": 45,
    "language": "Hungarian",
    "country": "Hungary",
    "content_rating": "R",
    "budget": 2500000000,
    "title_year": 2015,
    "actor_2_facebook_likes": 2,
    "imdb_score": 7.1,
    "aspect_ratio": 2.35,
    "movie_facebook_likes": 607
  }
]